// FILE TYPE: Entity class. One entity instance = one database row.
using System.ComponentModel.DataAnnotations; // Attributes like [Key], [Required].
using System.ComponentModel.DataAnnotations.Schema; // Attributes like [Table], [Column].

namespace Cars; // MUST match Part2.csproj RootNamespace and the DbContext namespace.

// TABLE MAPPING: Same as the table name `Cars` in `Cars.sql`:
// `CREATE TABLE Cars ( ... )`
[Table("Cars")]
public class Car
{
    // Primary key column in the database.
    [Key]
    [Column("ID")]
    // Surrogate key generated by SQLite AUTOINCREMENT.
    public int ID { get; set; }

    // SQL COLUMN: Same as column `Brand` in `Cars.sql`:
    // `Brand TEXT NOT NULL`
    [Required]
    [Column("Brand")]
    public string Brand { get; set; } = string.Empty;

    // SQL COLUMN: Same as column `Model` in `Cars.sql`:
    // `Model TEXT NOT NULL`
    [Required]
    [Column("Model")]
    public string Model { get; set; } = string.Empty;

    // SQL COLUMN: Same as column `CarsURL` in `Cars.sql`:
    // `CarsURL TEXT NOT NULL`
    [Required]
    [Column("CarsURL")]
    public string CarsUrl { get; set; } = string.Empty;
}
