using System.ComponentModel.DataAnnotations; // Attributes like [Key], [Required].
using System.ComponentModel.DataAnnotations.Schema; // Attributes like [Table], [Column].

namespace Orders; // MUST match Part2.csproj RootNamespace and the DbContext namespace.

// TABLE MAPPING: Same as the table name `Orders` in `Orders.sql`:
// `CREATE TABLE Orders ( ... )`
[Table("Orders")]
public class Order
{
    // Primary key column in the database.
    [Key]
    [Column("ID")]
    // Surrogate key generated by SQLite AUTOINCREMENT.
    public int ID { get; set; }

    // SQL COLUMN: Same as column `CustomerName` in `Orders.sql`:
    // `CustomerName TEXT NOT NULL`
    [Required]
    [Column("CustomerName")]
    public string CustomerName { get; set; } = string.Empty;

    // SQL COLUMN: Same as column `TotalAmount` in `Orders.sql`:
    // `TotalAmount TEXT NOT NULL`
    [Required]
    [Column("TotalAmount")]
    public string TotalAmount { get; set; } = string.Empty;

    // SQL COLUMN: Same as column `OrdersURL` in `Orders.sql`:
    // `OrdersURL TEXT NOT NULL`
    [Required]
    [Column("OrdersURL")]
    public string OrdersUrl { get; set; } = string.Empty;
}
