// FILE TYPE: Entity class. One entity instance = one database row.
using System.ComponentModel.DataAnnotations; // Attributes like [Key], [Required].
using System.ComponentModel.DataAnnotations.Schema; // Attributes like [Table], [Column].

namespace Movies; // MUST match Part2.csproj RootNamespace and the DbContext namespace.

// TABLE MAPPING: Same as the table name `Movies` in `Movies.sql`:
// `CREATE TABLE Movies ( ... )`
[Table("Movies")]
public class Movie
{
    // Primary key column in the database.
    [Key]
    [Column("ID")]
    // Surrogate key generated by SQLite AUTOINCREMENT.
    public int ID { get; set; }

    // SQL COLUMN: Same as column `MovieName` in `Movies.sql`:
    // `MovieName TEXT NOT NULL`
    [Required]
    [Column("MovieName")]
    public string MovieName { get; set; } = string.Empty;

    // SQL COLUMN: Same as column `Rating` in `Movies.sql`:
    // `Rating REAL NOT NULL`
    [Required]
    [Column("Rating")]
    public string Rating { get; set; } = string.Empty;

    // SQL COLUMN: Same as column `IMDbURL` in `Movies.sql`:
    // `IMDbURL TEXT NOT NULL`
    [Required]
    [Column("IMDbURL")]
    public string IMDbUrl { get; set; } = string.Empty;
}
