// FILE TYPE: Entity class file. An ENTITY is the C# shape of ONE database row.
// Example: one row in the Students table becomes one `Student` object in C#.

// ATTRIBUTE IMPORTS: used to mark keys and required fields.
using System.ComponentModel.DataAnnotations;
// ATTRIBUTE IMPORTS: used to map class/property names to SQL table/column names.
using System.ComponentModel.DataAnnotations.Schema;

// Must match Part2.csproj RootNamespace and my DbContext source file.
namespace Students;

// ENTITY CLASS: `Student` is an entity. EF Core uses it to represent rows from the database.
// TABLE MAPPING: MUST match the SQL table name in Students.sql:
//   `CREATE TABLE Students (...)`
[Table("Students")]
public class Student
{
    // Primary key column in the database.
    [Key]
    [Column("ID")]
    // Surrogate key generated by SQLite AUTOINCREMENT.
    public int ID { get; set; }

    // Column cannot contain null in the database.
    [Required]
    // This must match the SQL column name in Students.sql: `FullName TEXT NOT NULL`.
    [Column("FullName")]
    // ENTITY PROPERTY: used for sorting and display in the web page.
    // MUST match the Razor usage in Index.cshtml:
    //   `@student.FullName`
    public string FullName { get; set; } = string.Empty;

    // This must match the SQL column name in Students.sql: `GPA TEXT NOT NULL`.
    [Column("GPA")]
    // ENTITY PROPERTY: GPA string (you are not using it in the page right now).
    public string GPA { get; set; } = string.Empty;

    [Required]
    // This must match the SQL column name in Students.sql: `PortfolioURL TEXT NOT NULL`.
    [Column("PortfolioURL")]
    // ENTITY PROPERTY: Destination link shown in the Razor page anchor href.
    // MUST match the Razor usage in Index.cshtml:
    //   `href=\"@student.PortfolioUrl\"`
    public string PortfolioUrl { get; set; } = string.Empty;
}
