// FILE TYPE: Entity class. One entity instance = one database row.
using System.ComponentModel.DataAnnotations; // Attributes like [Key], [Required].
using System.ComponentModel.DataAnnotations.Schema; // Attributes like [Table], [Column].

namespace Books; // Same project namespace as Part2.csproj <RootNamespace> and BooksDbContext.cs.

// TABLE NAME: Same as the table name in `Books.sql`:
// `CREATE TABLE Books ( ... )`
[Table("Books")]
public class Book
{
    // Primary key column in the database.
    [Key]
    [Column("ID")]
    // Surrogate key generated by SQLite AUTOINCREMENT.
    public int ID { get; set; }

    // SQL COLUMN: Same as column `Title` in `Books.sql`:
    // `Title TEXT NOT NULL`
    [Required]
    [Column("Title")]
    public string Title { get; set; } = string.Empty;

    // SQL COLUMN: Same as column `Author` in `Books.sql`:
    // `Author TEXT NOT NULL`
    [Required]
    [Column("Author")]
    public string Author { get; set; } = string.Empty;

    // SQL COLUMN: Same as column `AmazonURL` in `Books.sql`:
    // `AmazonURL TEXT NOT NULL`
    [Required]
    [Column("AmazonURL")]
    public string AmazonUrl { get; set; } = string.Empty;
}
