// Validation attributes for non-null and key fields.
using System.ComponentModel.DataAnnotations;
// Table and column name mapping for EF Core.
using System.ComponentModel.DataAnnotations.Schema;

// Must match Part2.csproj RootNamespace and my DbContext source file.
namespace NewsSites;

// Maps to the SQL table name in [Table(...)]; column names must match my CREATE TABLE script.
[Table("NewsSites")]
// Entity type for each row listed on the home page.
public class NewsSite
{
    // Primary key column in the database.
    [Key]
    [Column("ID")]
    // Surrogate key generated by SQLite AUTOINCREMENT.
    public int ID { get; set; }

    // Column cannot contain null in the database.
    [Required]
    [Column("Name")]
    // Used when sorting the list alphabetically in Index.cshtml.cs (OrderBy Name).
    public string Name { get; set; } = string.Empty;

    [Required]
    [Column("URL")]
    // Destination link shown in the Razor page anchor href attribute.
    public string Url { get; set; } = string.Empty;
}
