// FILE TYPE: Entity class. One entity instance = one database row.
using System.ComponentModel.DataAnnotations; // Attributes like [Key], [Required].
using System.ComponentModel.DataAnnotations.Schema; // Attributes like [Table], [Column].

namespace Books; // MUST match Part2.csproj RootNamespace and the DbContext namespace.

// TABLE MAPPING: MUST match Books.sql: `CREATE TABLE Books (...)`
[Table("Books")]
public class Book
{
    // Primary key column in the database.
    [Key]
    [Column("ID")]
    // Surrogate key generated by SQLite AUTOINCREMENT.
    public int ID { get; set; }

    // ENTITY PROPERTY: visible title text in the list.
    // MUST match Books.sql: `Title TEXT NOT NULL`
    [Required]
    [Column("Title")]
    public string Title { get; set; } = string.Empty;

    // ENTITY PROPERTY: author (not shown on the list right now, but exists in the table).
    // MUST match Books.sql: `Author TEXT NOT NULL`
    [Required]
    [Column("Author")]
    public string Author { get; set; } = string.Empty;

    // ENTITY PROPERTY: link destination (Amazon URL) used in the Razor <a href="...">.
    // MUST match Books.sql: `AmazonURL TEXT NOT NULL`
    [Required]
    [Column("AmazonURL")]
    public string AmazonUrl { get; set; } = string.Empty;
}
